# Generated by Django 3.2.12 on 2025-04-18 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(help_text='Name of the coffee bean or blend', max_length=100)),
                ('water_amount_ml', models.PositiveIntegerField(blank=True, help_text='Amount of water used in ml', null=True)),
                ('bean_grams', models.DecimalField(blank=True, decimal_places=1, help_text='Amount of coffee beans used in grams', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('brew_method', models.CharField(choices=[('aeropress', 'Aeropress'), ('french_press', 'French Press'), ('espresso', 'Espresso'), ('latte', 'Latte'), ('cappuccino', 'Cappuccino'), ('freddo_espresso', 'Freddo Espresso'), ('greek_coffee', 'Greek Coffee'), ('pour_over', 'Pour Over'), ('drip', 'Drip Machine'), ('moka_pot', 'Moka Pot'), ('cold_brew', 'Cold Brew'), ('other', 'Other')], max_length=50)),
                ('steep_time', models.DurationField(blank=True, help_text='Steeping or brewing time (e.g., 00:04:00 for 4 minutes)', null=True)),
                ('rating', models.IntegerField(help_text='Your rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
