# Generated by Django 5.2 on 2025-04-18 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_coffeelog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeelog',
            name='grind_size',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Grind size setting on your grinder', max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='GrinderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grinder_name', models.CharField(max_length=100)),
                ('min_setting', models.IntegerField(default=1)),
                ('max_setting', models.IntegerField(default=40)),
                ('step_size', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grinders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coffeelog',
            name='grinder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffee_logs', to='activities.grindersetting'),
        ),
    ]
