# Generated by Django 3.2.12 on 2024-12-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
